Add adb client
kaponata-io/kaponata pull request #15
Opened 2021-01-20 13:30 UTC by bartsaintgermain

This PR adds a basic ADB client with currently two supported commands: GetAdbVersion and GetDevices.

2021-01-20 15:46 UTC, qmfrederik requested changes

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android.Tests/Adb/AdbClientCommandsTest.cs
> +        public async Task GetDevicesTestAsync()
I'm trying to use the "current best practice" naming conventions (whatever that entails) in this repository, something among the lines of:

1. The summary of the method states the `Fact` which is being validated, e.g. "The `GetDevicesAsync` method returns an device list`. That avoids having to write "Tests the..." or "Makes sure that..." prefix every time, which is a bit useless 😄 .
2. The name of a test method is `MethodName_ExpectedBehavior`, e.g. `GetDevices_ReturnsDeviceList` or something like that

See e.g. https://medium.com/@lorenzen.jacob/unit-test-naming-conventions-875786f53790

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbClient.Commands.cs
> +            return devices.ToList().Select(d => DeviceData.CreateFromAdbData(d));
Can we move `ToList` to the end and have the task return `List<DeviceData>` instead?

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbClient.cs
> +}
nit: new line at end of file

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +            return await this.ReadAdbResponseAsync(cancellationToken).ConfigureAwait(false);
I would vote to have `WriteMessageAsync` _not_ call `ReadAdbResponseAsync`, this should keep the code a bit cleaner.

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +            string status = await this.ReadStringAsync(4, cancellationToken).ConfigureAwait(false);
Instead of parsing these 4-byte responses as ASCII strings, we can just handle them as integers, and use an enum. E.g. 

```
enum AdbResponse : int
{
    OKAY = 0x4f4b4159,
}
```

It's a bit "hype du jour" but in the end it's just overhead to parse a 4-byte char value to a string and then compare it with another string, if an int comparison is sufficient. (And it's not by accident that all these values are 4 character longs and nicely fit in an int).

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +            var value = await this.ReadStringAsync(4, cancellationToken).ConfigureAwait(false);
It's a bit of overhead to parse an in from its ASCII-encoded hex value via a string, whereas you can just parse it directly from its binary representation.

Turns out I already wrote the code to do that: https://github.com/dotnet/Nerdbank.GitVersioning/blob/9803c2321b15676baaf4b4b015e8a7c09665c1a3/src/NerdBank.GitVersioning/ManagedGit/GitObjectId.cs#L94-L121

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +            var header = message.Length.ToString("X4");
This can be optimized as well:

- Get the length of the encoded string using `length = AdbEncoding.GetByteCount`
- Rent a buffer of size 4 + length
- Offset 0 through 3: the length (you can convert directly from the int value to a byte array without having to allocate an intermediate string)
- Offset 4 -end: `AdbEncoding.GetBytes`

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbSocketLocator.cs
> +            Socket socket;
The Muxer implementation has been updated to return a `Stream`, because in the end this was easier for mocking.

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbSocketLocator.cs
> +                var port = int.Parse(socketAddress[(separator + 1) ..]);
Nice 😄

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbSocketLocator.cs
> +            if (socketAddress != null && socketAddress.StartsWith("UNIX:", StringComparison.OrdinalIgnoreCase))
I don't think adb ever uses Unix sockets to communicate (even on Linux, adb will listen on a TCP socket). So this cause can probably go.

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbSocketLocator.cs
> +        public const string SocketAddressEnvironmentVariable = "ADB_SOCKET_ADDRESS";
I assumed adb had a standard environment variable you could set make `adb` always connect to that socket (like you can set `ADB_SERIAL`, and that we could reuse that "standard" name.

But it seems you always need to pass the `-H` and `-P` command line arguments, so this is fine.

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Adb/DeviceData.cs
> +}
nit: new line

2021-01-20 15:46 UTC, qmfrederik commented on src/Kaponata.Android/Properties/AssemblyInfo.cs
> +[assembly: InternalsVisibleTo("Kaponata.Android.Tests")]
Hmmm... Which internals do we need for unit testing? Does it make sense to make them public?

2021-01-21 09:33 UTC, qmfrederik commented
Based on this: https://android.googlesource.com/platform/system/core/+/dd7bc3319deb2b77c5d07a51b7d6cd7e11b5beb0/adb/OVERVIEW.TXT#77

I would expect something like this:

```csharp
interface IAdbProtocol
{
    Task Send(string payload, CancellationToken cancellationToken);
    Task Send(ReadOnlyMemory<byte> payload, CancellationToken cancellationToken);
    Task<AdbStatus> ReadStatus(CancellationToken cancellationToken);
    Task <string> ReadString(CancellationToken cancellationToken);
}

enum AdbStatus
{
    Okay,
    Fail,
}
```

And perhaps something like:

```csharp
async Task<string> GetSerialNumber(CancellationToken cancellationToken)
{
    await protocol.Send("<host-prefix>:get-serialno");
    if (await protocol.ReadStatus(cancellationToken) == AdbStatus.Fail)
    {
        var message = await protocol.ReadString(cancellationToken);
        throw new AdbException(message);
    }

    return await protocol.ReadString(cancellationToken);
```

perhaps witha helper method for read status + throw if failure at the client level?

2021-01-22 10:20 UTC, qmfrederik requested changes

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +        private static readonly byte[] ReverseHexDigits = BuildReverseHexDigits();
Perhaps move the hex-string-to-int conversion code to a separate class, e.g. `HexPrimitives` or so?

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +        internal Encoding AdbEncoding { get; set; } = Encoding.GetEncoding(DefaultEncoding);
Should this be a read-only `static` property?

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +        /// Reads the <c>ADB</c> response.
ADB => Adb. Applies throughout.

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +            using var messageBuffer = this.memoryPool.Rent(4);
Perhaps use `var messageBuffer = new stackalloc byte[4]`, this will avoid having to use the memory pool here.

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +            return BinaryPrimitives.ReadInt16BigEndian(intBuffer.Memory.Span);
If you read this as an `Int16`, FFFF will come back as -1 whereas you probably want it to be 65535. Should probably be `UInt16`.

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +            var b = int16Buffer.Memory.Span[0];
I would put this in a helper method - e.g. `void HexPrimitives.WriteUInt16(ushort value, Span<byte> memory)` or something like that.

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +                int c1 = ReverseHexDigits[messageBuffer.Memory.Span[i++] - '0'] << 4;
I would put this in a helper method - e.g. `ushort HexPrimitives.ReadUInt16(Span<byte> memory)` or something like that.

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbResponse.cs
> +        public static AdbResponse ADBSuccess { get; } = new AdbResponse(AdbResponseStatus.OKAY, string.Empty);
Either `AdbSuccess`, `Success` or `Okay`. I would go for `AdbResponse.Success`.

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbResponse.cs
> +    public class AdbResponse
This can be a `struct` instead.

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbResponse.cs
> +            this.FailMessage = message;
Keep the parameter name and the property name in sync. I would just go for `Message`.

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbResponseStatus.cs
> +        OKAY = 0x4f4b4159,
😄

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbResponseStatus.cs
> +    public enum AdbResponseStatus : int
Perhaps add a link to https://android.googlesource.com/platform/system/core/+/android-p-preview-4/adb/adb.h#39 where all possible values are defined.

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/DeviceState.cs
> +    public enum DeviceState
The original enum is named `ConnectionState`, https://android.googlesource.com/platform/system/core/+/android-p-preview-4/adb/adb.h#96, perhaps use the same name here.

Also, keep the same order

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/DeviceState.cs
> +        BootLoader,
Although a corner case, the Android code always cases it `Bootloader` (lower case l), so let's do the same here. (Also because `Sideload` is not cased `SideLoad`)

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbClient.Commands.cs
> +            var devicesResponse = await protocol.ReadAdbResponseAsync(cancellationToken).ConfigureAwait(false);
Should we validate the response?

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbClient.Commands.cs
> +            var devicesMessage = await protocol.ReadStringAsync(length, cancellationToken).ConfigureAwait(false);
Since a `string` is always prefixed with its length, I think it would be acceptable to just have `protocol.ReadString(CancellationToken)` which would read the length and then the string, right?

2021-01-22 10:20 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbClient.Commands.cs
> +            var response = await protocol.ReadAdbResponseAsync(cancellationToken).ConfigureAwait(false);
Should we validate the response?

2021-01-22 10:52 UTC, bartsaintgermain commented on src/Kaponata.Android/Adb/AdbClient.Commands.cs
> +            var devicesMessage = await protocol.ReadStringAsync(length, cancellationToken).ConfigureAwait(false);
Not always, in next PR (install apk) there is a case where the ADB server does not send the lenght.

2021-01-22 12:35 UTC, bartsaintgermain commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +        /// Reads the <c>ADB</c> response.
intention was:
in code: Adb
in comments ADB

2021-01-22 13:34 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +        /// Reads the <c>ADB</c> response.
OK

2021-01-22 16:30 UTC, qmfrederik commented on src/Kaponata.Android/Adb/AdbProtocol.cs
> +            if (status == AdbResponseStatus.OKAY.ToString())
I don't think this works - do we have a unit test covering this? OKAY.ToString() will not return "OKAY".

Instead, can we read the value as an Int32? E.g. 
```csharp
var buffer = stackalloc byte[4];
await this.stream.Read(buffer, cancellationToken).ConfigureAwait(false);
var status = (AdbResponseStatus)BinaryPrimitives.ReadInt32(buffer);

if (status == AdbResponseStatus.OKAY)
{
   ...
}
```

2021-01-23 21:36 UTC, qmfrederik commented
@bartsaintgermain Can we get the code coverage for `AdbProtocol` and `HexPrimitives` to 100%? Otherwise: LGTM

2021-01-25 15:37 UTC, qmfrederik approved these changes

2021-01-25 15:37 UTC, merged