UI/e2e test
kaponata-io/kaponata pull request #257
Opened 2021-05-18 13:15 UTC by bartsaintgermain

2021-05-20 14:46 UTC, qmfrederik requested changes

2021-05-20 14:46 UTC, qmfrederik commented on .github/workflows/build.yaml
> +
nit: whitespace

2021-05-20 14:46 UTC, qmfrederik commented on .github/workflows/ui-test.yaml
> +          ansible-galaxy install geerlingguy.nodejs
I guess this is not really needed?

2021-05-20 14:53 UTC, bartsaintgermain commented on .github/workflows/build.yaml
> +
seems there was a missing whitespace

2021-05-21 07:48 UTC, qmfrederik commented on .github/workflows/ui-test.yaml
> +      - name: Provision CI environment
Do we need this?

2021-05-21 07:49 UTC, qmfrederik approved these changes

2021-05-21 08:14 UTC, merged